from django.contrib import admin
from .models import Student, Professor, Term, Food, FoodReservation, ProfessorRating, Course, Day, Room, Class, Attendance, CourseRegistration, Department, Grade, Announcement, Assignment, ExaminationSchedule, Messages

admin.site.register(Student)
admin.site.register(Professor)
admin.site.register(Term)
admin.site.register(Food)
admin.site.register(FoodReservation)
admin.site.register(ProfessorRating)
admin.site.register(Course)
admin.site.register(Day)
admin.site.register(Room)
admin.site.register(Class)
admin.site.register(Attendance)
admin.site.register(CourseRegistration)
admin.site.register(Department)
admin.site.register(Grade)
admin.site.register(Announcement)
admin.site.register(Assignment)
admin.site.register(ExaminationSchedule)
admin.site.register(Messages)